version: '3.8'
services:
  web:
    image: nginx:alpine
    working_dir: /application
    depends_on:
        - backend
    volumes:
     - .:/application
     - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - ${WEB_PORT}:80

  backend:
    build: ./docker/php
    working_dir: /application
    volumes:
      # - ./backend-laravel:/application
      - .:/application
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
