version: '3.8'
services:
  web:
    image: nginx:alpine
    working_dir: /application
    volumes:
     - .:/application
     - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - ${WEB_PORT}:80
